
services:
  postgres:
    image: postgres:15-alpine
    container_name: benchmarking_postgres
    environment:
      POSTGRES_DB: analytics_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d analytics_db"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
